WebAppArte/Models/Artist.cs
namespace WebAppArte.Models
{
    public class Artist
    {
        public int ID { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Country { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
    }
}

WebAppArte/Models/ErrorViewModel.cs
namespace WebAppArte.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppArte/Models/Paint.cs
using System.ComponentModel.DataAnnotations;

namespace WebAppArte.Models
{
    public class Paint
    {

        public int ID { get; set; }

        [Required]
        public string Name { get; set; } = string.Empty;

        [Required]
        public string Type { get; set; } = string.Empty;

        [Required]
        public string Description { get; set; } = string.Empty;
    }
}

WebAppArte/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Text.Json.Serialization;
using WebAppArte.Models;
using Newtonsoft.Json;
using System.Text;

namespace WebAppArte.Controllers
{
    public class HomeController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7021/api");
        private readonly HttpClient _httpClient;

        public HomeController(ILogger<HomeController> logger)
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }

        public IActionResult Index()
        {
            return View();
        }

        public  IActionResult Artist()
        {

            List<Artist> artistLst = new List<Artist>();
            
            return View(artistLst);
        }
        public async Task<IActionResult> GetArtist()
        {
          
            List<Artist> artistLst=new List<Artist>() ;
            HttpResponseMessage response = await _httpClient.GetAsync(_httpClient.BaseAddress+"/artist/GetArtist");

            if (response.IsSuccessStatusCode)
            {
                //listaArtista = await response.Content.ReadAsStringAsync();
                string data=  response.Content.ReadAsStringAsync().Result;
                artistLst = JsonConvert.DeserializeObject<List<Artist>>(data);
            }
            else
            {
                ErrorViewModel error=new ErrorViewModel();
                error.RequestId = response.StatusCode.ToString();
                return View("Error",error);
            }
           
            return View("Artist",artistLst);
        }


        public IActionResult Edit(Artist artist)
        {
            return View(artist);
        }


        public async Task<IActionResult> Delete(int ID)
        {

            List<Artist> ArtistLst = new List<Artist>();
            HttpResponseMessage response = await _httpClient.DeleteAsync(_httpClient.BaseAddress + "/artist/DeleteArtist?ID=" + ID);

            if (response.IsSuccessStatusCode)
            {
                response = await _httpClient.GetAsync(_httpClient.BaseAddress + "/artist/GetArtist");

                if (response.IsSuccessStatusCode)
                {
                    //listaArtista = await response.Content.ReadAsStringAsync();
                    string data = response.Content.ReadAsStringAsync().Result;
                    ArtistLst = JsonConvert.DeserializeObject<List<Artist>>(data);
                }
                else
                {
                    ErrorViewModel error = new ErrorViewModel();
                    error.RequestId = response.StatusCode.ToString();
                    return View("Error", error);
                }


            }

            return View("Artist", ArtistLst);
        }

        public async Task<IActionResult> PostArtist(Artist artist)
        {
            
            Artist artistResponse = new Artist();
            
            HttpContent content = new StringContent(JsonConvert.SerializeObject(artist), Encoding.UTF8, "application/json");

            HttpResponseMessage response = await _httpClient.PostAsync(_httpClient.BaseAddress + "/artist/PostArtist", content);


            if (response.IsSuccessStatusCode)
            {
                //listaArtista = await response.Content.ReadAsStringAsync();
                string data = response.Content.ReadAsStringAsync().Result;
                artistResponse = JsonConvert.DeserializeObject<Artist>(data);

            }
            else
            {
                ErrorViewModel error = new ErrorViewModel();
                error.RequestId = response.StatusCode.ToString();
                return View("Error", error);
            }

            return View("Edit", artistResponse);
         
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppArte/Controllers/PaintController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebAppArte.Models;

namespace WebAppArte.Controllers
{
    public class PaintController : Controller
    {

        Uri baseAddress = new Uri("https://localhost:7021/api");
        private readonly HttpClient _httpClient;


        public PaintController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }
     

        public async Task<IActionResult> Index(int ID)
        {

            List<Paint> PaintLst = new List<Paint>();
            HttpResponseMessage response = await _httpClient.GetAsync(_httpClient.BaseAddress + "/paint/GetAPaint?ID=" + ID);
            ViewData["IDArtist"] = ID;
            if (response.IsSuccessStatusCode)
            {
                //listaArtista = await response.Content.ReadAsStringAsync();
                string data = response.Content.ReadAsStringAsync().Result;
                PaintLst = JsonConvert.DeserializeObject<List<Paint>>(data);
            }
            else if(response.StatusCode!=System.Net.HttpStatusCode.NotFound)
            {
                ErrorViewModel error = new ErrorViewModel();
                error.RequestId = response.StatusCode.ToString();
                return View("Error", error);
            }


            return View("Index", PaintLst);
        }

        public async Task<IActionResult> Delete(int ID,int IDArtist)
        {

            List<Paint> PaintLst = new List<Paint>();
            HttpResponseMessage response = await _httpClient.DeleteAsync(_httpClient.BaseAddress + "/paint/DeletePaint?ID=" + ID);
            ViewData["IDArtist"] = IDArtist;
            if (response.IsSuccessStatusCode)
            {
                 response = await _httpClient.GetAsync(_httpClient.BaseAddress + "/paint/GetAPaint?ID=" + IDArtist);

                if (response.IsSuccessStatusCode)
                {
                    //listaArtista = await response.Content.ReadAsStringAsync();
                    string data = response.Content.ReadAsStringAsync().Result;
                    PaintLst = JsonConvert.DeserializeObject<List<Paint>>(data);
                }
                else if(response.StatusCode != System.Net.HttpStatusCode.NotFound)
                {
                    ErrorViewModel error = new ErrorViewModel();
                    error.RequestId = response.StatusCode.ToString();
                    return View("Error", error);
                }


            }

            return View("Index", PaintLst);
        }
    }
}

WebAppArte/Views/Home/Artist.cshtml
@model IEnumerable<WebAppArte.Models.Artist>

@{
    ViewData["Title"] = "Artist";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
   <button name="button" onclick="ShowTable()">Mostrar información</button>
</div>

<h1>Artista</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new {  ID=item.ID, Name=item.Name, Country=item.Country, Description=item.Description }) |
                @Html.ActionLink("Detalles", "Index","Paint", new { ID=item.ID }) |
                @Html.ActionLink("Eliminar", "Delete", new { ID=item.ID }) |
               
            </td>
        </tr>
}
    </tbody>
</table>

@if(Model.Count()==0){
    <div class="text-center">
  No hay información
</div>
}
<script>
function ShowTable() {
    
    window.location = '@Url.Action("GetArtist", "Home")'; 
}

</script>

WebAppArte/Views/Home/Edit.cshtml
@model Artist
@{
    ViewData["Title"] = "Home Page";
}



<div class="text-center">
   <button name="button" onclick="BackMaster()">Regresar</button>
</div>


<div style="margin-bottom:5px" class="text-center">
   Nombre
   <input type="text" id="nombre" name="nombre" />
</div>

<div  style="margin-bottom:5px" class="text-center">
    Pais
   <input type="text" id="pais" name="pais" />
</div>

<div  style="margin-bottom:5px" class="text-center">
    Descripcion
   <input type="text"  id="descripcion" name="descripcion" />
</div>

<div class="text-center">
   <button name="button" onclick="Actualizar()">Actualizar</button>
</div>

<script>
     document.getElementById("nombre").value = '@Model.Name'; 
     document.getElementById("pais").value = '@Model.Country';
     document.getElementById("descripcion").value = '@Model.Description';

     
     
    function Actualizar() {

        var nombre=document.getElementById("nombre").value;
        var pais=document.getElementById("pais").value;
        var descripcion= document.getElementById("descripcion").value;

        var resultado=Validaciones(nombre,pais,descripcion);
    
        if(resultado==0){
             window.location = '@Url.Action("PostArtist", "Home")?ID=' + @Model.ID+'&Name='+nombre+'&Country='+pais+'&Description='+descripcion; 
        }
    }


    function  Validaciones(nombre,pais,descripcion){
        var resultado=0;
        if(nombre == "" || pais== "" || descripcion==""){
            alert("Nombre, pais y descripcion son obligatorios");
            resultado=1;
        }
        
        if(nombre.length>100){
            alert("Nombre debe ser menor a 100 caracteres");
             resultado=1;
        }

         if(pais.length>100){
            alert("Pais debe ser menor a 100 caracteres");
             resultado=1;
        }

         if(descripcion.length>250){
            alert("Descripcion debe ser menor a 250 caracteres");
             resultado=1;
        }
        return resultado;
    }


    function BackMaster(){
         window.location = '@Url.Action("GetArtist", "Home")'; 
    }

</script>

WebAppArte/Views/Home/Index.cshtml
@model List<Artist>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
   <button name="button" onclick="location.href='@Url.Action("GetAllArtist", "Home")'">Mostrar información</button>
</div>

WebAppArte/Views/Paint/Index.cshtml
@model IEnumerable<WebAppArte.Models.Paint>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
   <button name="button" onclick="BackMaster()">Artistas</button>
</div>

<h1>Pinturas</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
              
                <a href="#" onclick="Delete(@item.ID,@ViewData["IDArtist"])">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

@if(Model.Count()==0){
    <div class="text-center">
  No hay información para mostrar

</div>
 }
<script>

    function Delete(ID,IDArtist){
        var resultado=confirm("Esta seguro de eliminar el registro ?");
        if(resultado==true){
            window.location = '@Url.Action("Delete", "Paint")?ID='+ID+"&IDArtist="+IDArtist; 
        }

    }
    
    function BackMaster(){
         window.location = '@Url.Action("GetArtist", "Home")'; 
    }
</script>

WebAppArte/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Arte</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppArte.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppArte</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Artist">Artist</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebAppArte - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>